name: HostNameWhiteList
version: 1.5
author: EDawg878
main: com.edawg878.hostnamewhitelist.bukkit.BukkitHostNameWhiteList
commands:
  hostnamewhitelist:
    aliases: hnw
    permission: hostnamewhitelist.admin